### ISSUE TITLE
not work at ie11

### ISSUE THREAD

**Issue by chubbyerror** [ch3rub1m/que#1]
难道这是nodejs的后端不是前端吗？？？！！！？！？！

**Comment by ch3rub1m** [comment]
@chubbyerror ie11需要先编译再使用，你编译了吗

**Comment by chubbyerror** [comment]
应该没有编译……前端也要编译了？？！！？！？！

**Comment by ch3rub1m** [comment]
@chubbyerror 对的，我更新了readme了，你需要先安装yarn，然后在终端输入1.yarn 2.yarn run dev，浏览器应该会自动打开

**Comment by chubbyerror** [comment]
………………安装软件困难，下班再说吧。
谢谢哦
