### ISSUE TITLE
que tan

### ISSUE THREAD

**Issue by tppppppppp** [ch3rub1m/que#3]
阙坦？

**Comment by ch3rub1m** [comment]
> 阙坦？

唐攀攀？

**Comment by tppppppppp** [comment]
> > 阙坦？
> 
> 唐攀攀？

是啊，long time no see~

**Comment by ch3rub1m** [comment]
> > > 阙坦？
> > 
> > 
> > 唐攀攀？
> 
> 是啊，long time no see~

hah，感觉快十年没见了

**Comment by tppppppppp** [comment]
为啥在你的git里没看到当年写的五子棋，好像还带ai来着

**Comment by ch3rub1m** [comment]
> 为啥在你的git里没看到当年写的五子棋，好像还带ai来着

那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。

我现在对算法那块已经不怎么关注了，就是玩一玩。

**Comment by tppppppppp** [comment]
> > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> 
> 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> 
> 我现在对算法那块已经不怎么关注了，就是玩一玩。

那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~

**Comment by ch3rub1m** [comment]
> > > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> > 
> > 
> > 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> > 我现在对算法那块已经不怎么关注了，就是玩一玩。
> 
> 那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~

感觉第一个比较完整的是C语言课的学生管理系统，是个命令行程序，第一个带界面的是Java课的图书管理系统，五子棋是MFC的，但是实际上我并不懂MFC，所以在我心里，五子棋那个程序是瞎写的，不能算真正的程序。

**Comment by ch3rub1m** [comment]
> > > > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> > > 
> > > 
> > > 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> > > 我现在对算法那块已经不怎么关注了，就是玩一玩。
> > 
> > 
> > 那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~
> 
> 感觉第一个比较完整的是C语言课的学生管理系统，是个命令行程序，第一个带界面的是Java课的图书管理系统，五子棋是MFC的，但是实际上我并不懂MFC，所以在我心里，五子棋那个程序是瞎写的，不能算真正的程序。

学生管理系统还在我的学校邮箱里存着，有空的话可以整理出来，嘻嘻

**Comment by ch3rub1m** [comment]
> > > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> > 
> > 
> > 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> > 我现在对算法那块已经不怎么关注了，就是玩一玩。
> 
> 那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~

不过我的技术栈经历了无数次变化以后，就觉得以前写的代码完全不符合最佳实践了，比如这个que，也是瞎写的。

**Comment by tppppppppp** [comment]
> > > > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> > > 
> > > 
> > > 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> > > 我现在对算法那块已经不怎么关注了，就是玩一玩。
> > 
> > 
> > 那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~
> 
> 不过我的技术栈经历了无数次变化以后，就觉得以前写的代码完全不符合最佳实践了，比如这个que，也是瞎写的。

你现在主要写go吗，之前带我的师兄对它很推崇，听他说性能超好，我还没用过

**Comment by tppppppppp** [comment]
> > > > > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> > > > 
> > > > 
> > > > 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> > > > 我现在对算法那块已经不怎么关注了，就是玩一玩。
> > > 
> > > 
> > > 那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~
> > 
> > 
> > 感觉第一个比较完整的是C语言课的学生管理系统，是个命令行程序，第一个带界面的是Java课的图书管理系统，五子棋是MFC的，但是实际上我并不懂MFC，所以在我心里，五子棋那个程序是瞎写的，不能算真正的程序。
> 
> 学生管理系统还在我的学校邮箱里存着，有空的话可以整理出来，嘻嘻

好像是有个学生管理系统，我都没什么印象了，反而对你的五子棋印象比较深刻，比我写的那个好多了，我记得当你是你的棋子用的是贴图，我用画笔画的，相形见绌。。。

**Comment by ch3rub1m** [comment]
> > > > > > 为啥在你的git里没看到当年写的五子棋，好像还带ai来着
> > > > > 
> > > > > 
> > > > > 那也太古老了吧，那种代码早就丢了啊哈哈，只是个玩具，不能算AI，之前倒是想过写一个基于蒙特卡洛树的象棋AI，不过太忙了，就搁置了。
> > > > > 我现在对算法那块已经不怎么关注了，就是玩一玩。
> > > > 
> > > > 
> > > > 那应该是第一个比较完整的程序吧，从此开启了漫长的程序生涯，比较有纪念意义~
> > > 
> > > 
> > > 感觉第一个比较完整的是C语言课的学生管理系统，是个命令行程序，第一个带界面的是Java课的图书管理系统，五子棋是MFC的，但是实际上我并不懂MFC，所以在我心里，五子棋那个程序是瞎写的，不能算真正的程序。
> > 
> > 
> > 学生管理系统还在我的学校邮箱里存着，有空的话可以整理出来，嘻嘻
> 
> 好像是有个学生管理系统，我都没什么印象了，反而对你的五子棋印象比较深刻，比我写的那个好多了，我记得当你是你的棋子用的是贴图，我用画笔画的，相形见绌。。。

哈哈，过奖了，这里聊天不太方便，可以加一下我微信，我微信号就是我github账号
